Issue64
PatrickWeller/PanelPal pull request #81
Opened 2024-12-02 16:35 UTC by RVel37

### Code changes
This pull request addresses several improvements, including some items from issue #64 (generate_bed.py improvements):

- Adds padding around exons (+10 bases on either side) in the final BED file.
- Concatenates the final columns of the intermediate BED file (the exon number, gene symbol, and transcript reference).

Additionally, it resolves issue #63 (Edit rate-limiting function) by replacing the previous retry logic for handling rate limits. VariantValidator’s rate-limiting function was used as a reference for our code’s rate limit, reducing the number of retries required. 

Formatting improvements were also made:
- Added docstrings to database scripts for better documentation.
- Moved the database test script to the correct `tests` directory, fixing previous issues caused by misplacement. 
- Edited scripts to be PEP-8 compliant.
- Refactored logging messages in the modified scripts to use lazy loading. This makes it so log messages are only evaluated and formatted when they are actually logged, improving performance by avoiding unnecessary string concatenation when logging is disabled. 

No new tests, dependencies or requirements introduced. 

Also solved merge conflicts (I hope). 

### Pylint reviews for modified scripts:
Both 10/10. 
accessories/variant_validator_api_functions.py: 
![image](https://github.com/user-attachments/assets/8b6f6354-215d-4876-9190-f03f56a8854c)

DB/setup.py: 
![image](https://github.com/user-attachments/assets/5bbcec84-840f-45eb-a2b5-b9bf8869d5f3)

### Action required
I've been having issues with running tests, specifically related to the file paths. I'm trying to figure it out but in the meanwhile I'd be super grateful for some assistance; please feel free to make any changes or suggestions as needed.

2024-12-03 11:10 UTC, RVel37 commented
I've since figured out how to get tests up and running, and all the DB-related tests pass. Currently working on fixing a couple of failures in `test_variantvalidator.py`.

2024-12-03 11:34 UTC, RVel37 commented
I've fixed the failures in `test_variantvalidator.py` now. 
The function `extract_exon_info` in `variant_validator_api_functions.py` was returning an empty list in the test because it wasn't accessing the right part of the tuple in `exon_structure`. I added code to access the value part of the tuple. 
```bash
$ pytest ../test/
../test/test_variantvalidator.py .... 
../test/test_variantvalidator.py .... 
```

2024-12-04 11:02 UTC, PatrickWeller requested changes
Hi Ray,

I'm no expert in our code so have only commented on the stuff that I understand really! I've left some comments for you about some things to check over of change. Thanks

2024-12-04 11:02 UTC, PatrickWeller commented on test/test_panelapp.py
Thanks for neatening up this file to make it PEP8 compliant. I hadn't ran pylint on my test files, wasn't sure if it was needed. The file looks much neater now though, thanks!. 
You'll see here though that there are a few more tests at the bottom of this file in development. Would you mind making sure these tests are added to your branch. Thanks.

2024-12-05 22:41 UTC, RVel37 commented on DB/setup.py
>  logger = logging.getLogger(__name__)
Fixed, sorry I forgot to update after we introduced the centralised logger script.

2024-12-05 22:57 UTC, RVel37 commented on DB/setup.py
> +        sqlite3.Error: an exception is raised and logged if the connection fails.
Fixed issues using chatgpt and checked style guides.

2024-12-05 23:05 UTC, RVel37 commented on DB/setup.py
>      """
Fixed, also checked pylint compliance (10/10)

2024-12-05 23:13 UTC, RVel37 commented on PanelPal/__pycache__/__init__.cpython-312.pyc
Deleted pycache files. I did wonder the same - I think the reason they keep reappearing may be simply that they were lurking in my local branch from before they were excluded in the .gitignore. Hopefully they'll stop appearing from now on.

2024-12-06 00:18 UTC, RVel37 commented on test/db_tests/test_db.py
Here's the output for the coverage report:
```
test_db.py                                             32      2    94%   154, 158
```
When writing unit tests for the database, I read that it's common to use a mock in-memory database to avoid modifying the actual data when testing, so `test_db.py` doesn't directly test the actual database but instead tests the same logic in isolation using this mock database. When it comes to integrating the app with the real database, we can add integration tests to make sure the app connects and executes queries (like SELECT, INSERT, UPDATE, DELETE). There's a package called `pytest-sqlalchemy` that can manage test databases and may be helpful but honestly I'm still working on it/doing background reading.

2024-12-06 00:21 UTC, RVel37 commented on PanelPal/panelpal.db
Yep sorry, added to gitignore

2024-12-06 00:30 UTC, RVel37 commented on test/test_panelapp.py
All done. On my machine I have a setting to run Black on save, which allows for quick reformatting and I've found it very useful for PEP8 compliance.

2024-12-06 00:32 UTC, RVel37 commented on PanelPal/accessories/variant_validator_api_functions.py
> +import logging
Done

2024-12-06 00:42 UTC, RVel37 commented on PanelPal/accessories/variant_validator_api_functions.py
>          Exception: If the request to the API fails (status code not 200).
Numpy docstring compliance added for all functions in the script - I hope they're ok, let me know if they aren't

2024-12-06 01:05 UTC, RVel37 commented
To resolve the merge conflicts above with the web editor, you can simply delete this section from setup.py:

```
<<<<<<< issue64
=======
logging.basicConfig(
    level=logging.DEBUG, 
    # format debugging messages (timestamp, name of logger, level of log message, actual message.)
    format='%(asctime)s - %(name)s - %(levelname)s - %(message)s',
    handlers=[
        logging.FileHandler("logging/DBsetup.log"), # store logs here
        logging.StreamHandler() # print to stdout as well
    ]
)
>>>>>>> development
```
and this section from .gitignore:

```
=======
PanelPal/PanelPal.egg-info
PanelPal/__pycache__/
test/__pycache__/
__pycache__/
*.bed
*.log
DB/
>>>>>>> development
```
I don't think I can save these changes without committing the merge.

2024-12-06 09:35 UTC, merged